### ISSUE TITLE
How to produce the json

### ISSUE THREAD

**Issue by ramiel** [alexanderwallin/lioness#13]
Hello, first af all thanks for this component!
I have a question. I have a folder with several po files. How can I produce a json file to feed the provider? The documentation is not clear (also on node-gettext project). I can create a gettext instance with all the messages, but then the provider needs a json and I cannot get it from the gettText instance.
Then I saw that internally the provider transforms messages into a gettext instace again, so why can't it accept an instance itself?

**Comment by alexanderwallin** [comment]
Hi @ramiel! Thanks for raising the issue. I agree the documentation can be improved.

You should not have to interface with `node-gettext` yourself, although being able to pass your own instance of it sounds like a good idea.

You create the JSON files using [gettext-parser](https://github.com/smhg/gettext-parser)!

**Comment by ramiel** [comment]
It's what I'm actually doing with this code:

```js
const fs = require('fs');
const path = require('path');
const { po } = require('gettext-parser');

const translationsDir = `${__dirname}/src/i18n/`;
const locales = [{
  locale: 'itIT',
},
{
  locale: 'enEN',
  file: 'message.pot',
}];

const messages = {};

locales.forEach(({ locale, file = null }) => {
  const fileName = file || `${locale}.po`;
  const translationsFilePath = path.join(translationsDir, fileName);
  const translationsContent = fs.readFileSync(translationsFilePath);

  messages[locale] = po.parse(translationsContent);
});

fs.writeFileSync(path.join(translationsDir, 'translations.json'), JSON.stringify(messages, null, '  '));
```

I think I'm going to create a babel plugin to create this file otherwise this part will lack automation.Now you can automatically create a pot file but not the needed json.

**Comment by alexanderwallin** [comment]
And using the contents from `translations.json` is not working?

**Comment by ramiel** [comment]
Yes, it works.But I have to produce it every time I change the content of any po file. This could be done automatically I guess.

**Comment by alexanderwallin** [comment]
It could indeed!

**Comment by alexanderwallin** [comment]
I would be happy to be updated on whatever you create! Would probably come in handy. :)
