### ISSUE TITLE
`withTranslators` behavior without a `LionessProvider`

### ISSUE THREAD

**Issue by phtrivier** [alexanderwallin/lioness#19]
It seems like, when a component built from `withTranslators` is not a child of a `LionessProvider`, it is passed `null` as props for `t`, `tc`, tc...

I would find it helpfull to pass a "friendlier" default (eg the identity function), for example in tests or storybooks. Is there a fundamental reason not to do that ?

**Comment by alexanderwallin** [comment]
`withTranslators()` only works inside `<LionessProvider>`, so I think it's only natural it breaks. Maybe it should even warn in the console?

But when it comes to tests, then perhaps it would be useful with an official mock/stub to make writing tests easier? Do you have a particular example?

Never thought about storybooks! How would that look?

**Comment by phtrivier** [comment]
For storybook, I meant https://github.com/storybooks/storybook. 
For the moment, I created a 'DummyLionessProvider' that injects an empty language configuration, and I wrap all my components inside it. 
That does the job, but it's a bit annoying.

However, I could definitely imagine a `withDefaultTranslator` hoc (or being able to pass options to withTranslator) so that, when the component is renderered with no provider in the context, it does "the best it can").  Assuming the messages passed to `t` are always the "default" (aka 'english' :/ ) version of the text, that would work.

**Comment by alexanderwallin** [comment]
Your `<DummyLionessProvider>` is indeed a good way of doing it, but yeah, a bit cumbersome.

I think since this only relates to tests or testing environments, we should not touch the original source, but instead provide testing tools.

I'll come with a suggestion as soon as I can!

**Comment by phtrivier** [comment]
Just for info, I ended switching to jed, because the approach of using a single global function to do translations (rather than injecting them with an hoc) was better suited to my project. 
Thanks for the lib anyway !

**Comment by alexanderwallin** [comment]
Fair enough! Thanks for pointing that out. I've had in my mind to simply the API in that direction, although keeping the HOC pattern.

Good luck with your project!

**Comment by alexeychikk** [comment]
@antonvialibri1 Hi, im not really sure I am the one to answer this question because I haven't used this library for years and I am not involved in its development.
