### ISSUE TITLE
Html interpolation

### ISSUE THREAD

**Issue by ramiel** [alexanderwallin/lioness#23]
I have this string

`Go to <a href="{{ link }}>{{ link }}</a> and insert the code {{ code }}`

How should I write the <T> and the translation string?

If I write it like this

```jsx
<T
      message="Go to {{ link }} and insert the code {{ code }}"
      link={<a href={url}>{url}</a>}
      code={code}
 />
```

but it does not work. The problem, of course, is the anchor

**Comment by alexanderwallin** [comment]
You can check the example in the README. Anything after a colon inside a template variable (`{{ link:text inside link }}`) is injected into the passed component (`link={<a href={url} />}`).

In your case you need to add the `url` after the colon, like so:

```js
<T
  message={`Go to {{ link:${url} }} and insert the code {{ code }}`}
  link={<a href={url} />}
  code={code}
/>
```

**Comment by alexanderwallin** [comment]
Closing this in favour of https://github.com/alexanderwallin/lioness/issues/25

**Comment by alexanderwallin** [comment]
@ramiel You can do it your way now! See https://github.com/alexanderwallin/lioness/commit/e3330e30eca944ec2618921fc4eb769e1cdee335
