### ISSUE TITLE
A parser between JSON and .po/.mo files is not obvious.

### ISSUE THREAD

**Issue by oolleegg55** [alexanderwallin/lioness#26]
Hello 😄 

This issue is not an issue in fact. I have some thoughts about compiling "po" files to "JSON".  
Yesterday I came across with setting up full sequence for i18n my app. And everything was OK but not a step of PO to JSON. It took me several hours to set it up. 
There are a few misconceptions for Gulp users. 
First, gulp plugin https://www.npmjs.com/package/gulp-po2json does wrong JSON format. 
Second, gettext-parser hasn't gulp plugin 😸 

OK, it figured it out or maybe I googled not in a right way 😄 
I started to read about gulp plugins and how to build it. Buffers, streams and bla bla bla. Two hours and I am ready 🚀 
But it appears, that gettext-parser builds the wrong JSON too! It was very funny. This JSON hadn't a root node with a locale which was required. 
Finally, I got what I wanted.
Something like this:
```js
gulp.task('build:po2json', function () {
	return gulp.src(['translations/**/*.po'])
		.pipe(through2.obj(function (chunk, enc, callback) {
			if ( chunk.isBuffer ) {
				let po = gettextParser.po.parse(chunk.contents.toString());
				let poObj = {
					[po.headers.language]: {...po}
				};

				chunk.contents = new Buffer(JSON.stringify(poObj));
				chunk.path = replaceExt(chunk.path, '.json');
			}

			callback(null, chunk);
		}))
		.pipe(gulp.dest('translations/'));
});
```
And now my question: 😄 
Is this theme regard common instruction and should it be presented here? 
If it took me (as a newbie) for a few hours, it could be helpful for somebody too.
What do you think?

**Comment by alexanderwallin** [comment]
Hi Oleg! If you are having this issue, then it is an issue. There can definitely be improvements made to better guide people in getting started. I'll leave this issue open and let you know when I've made any changes.

**Comment by oolleegg55** [comment]
Well. I could had done PR but I don't know a format of a guide you use and where to put this information. 
So, I will wait you are getting started.

**Comment by oolleegg55** [comment]
I've closed this issue because I haven't got use cases for this and this issue is opened for 2.5 years without moving forward.
