### ISSUE TITLE
How to use lioness outside of a component

### ISSUE THREAD

**Issue by ezelohar** [alexanderwallin/lioness#30]
Question is simple. Let's say a component have a default prop with some text as value.  How to use lioness on them? 
Thank you, and sorry for posting this on the issues page.

**Comment by iszak** [comment]
Hello @ezelohar, you would need to create an instance of GetText which is used internally for translation. 

You may be able to import the internal constructor https://github.com/alexanderwallin/lioness/blob/master/src/getGettextInstance.js#L5 however, I'm not sure if this is for public consumption.

An example usage can be found here https://github.com/alexanderwallin/lioness/blob/master/src/components/LionessProvider.js#L36

**Comment by alexanderwallin** [comment]
Technically, you could just pass the prop to a fitting translator functions provided through [`withTranslators()`](https://github.com/alexanderwallin/lioness#withtranslationscomponent):

```js
<button>{this.props.t(this.props.buttonLabel)}</button>
```

**Comment by iszak** [comment]
Ah yes, I believe if there is no translation it uses the default string.

**Comment by alexanderwallin** [comment]
@ezelohar May I ask what your scenario is?

**Comment by VladislavDolgolenko** [comment]
Do not use translations methods without component, it is conceptual incorrect.

Component has state and triggered when changing "local". You lose translation on fly If your use translate functions out of component.

**Comment by alexanderwallin** [comment]
Thanks for the comment, @VladislavDolgolenko!

Closing this now.

**Comment by ezelohar** [comment]
Hi @VladislavDolgolenko 
The use case is simple. You have some "global" data which needs a translation and it doesn't belong to a single component, but it is just "reusable" data.
