### ISSUE TITLE
What's the relation between Lioness and react-targem?

### ISSUE THREAD

**Issue by honi** [alexanderwallin/lioness#38]
It seems like both projects are very similar and even share some contributors. I would like to understand the history behind this proyect because it fits my needs and I like the approach but I don't want to invest using a library that might be discontinued in the short term.

Thanks!

**Comment by alexanderwallin** [comment]
I didn't know about react-targem. It's obviously initially a copy of Lioness that has branched out. Too bad they didn't try to join forces and improve what was already there.

As it is now, Lioness is improved whenever I (or someone else) bump into new requirements. The feature that's next in the pipeline of being added is nested component interpolation:

```
<T
  message="You need {{ docsLink:read {{ strong:and }} write permissions }} to do this"
  strong={<strong />}
  docsLink={<a href="docs.com" />}
/>
```

I've been thinking about a revamp with a much smaller and nicer API, hooks, increased modularity and React Native support, but I can't say when this'll happen. It would be great to put together a `@lioness/*` suite of packages.

For your sake, you'll have to judge yourself. react-targem looks fairly active, bit Lioness is not stale either.

**Comment by honi** [comment]
Thank you very much for your response.

**Comment by alexeychikk** [comment]
@alexanderwallin Yes, I partially copied the readme and interpolation function but the rest of the library was written from scratch.
The main reasons why `react-targem` exists are described here: https://github.com/trucknet-io/react-targem/issues/26#issuecomment-697052088

Also, Trucknet.io (the company I worked for) needed a reliable localization solution that we could actively modify and extend to feet our needs, without the need to wait until the PR is review and accepted.

**Comment by alexanderwallin** [comment]
Thanks for clarifying, @alexeychikk!

I take it you're not employed there anymore? I was thinking about maybe suggesting to join the two sets of tools into one at some point.

**Comment by alexeychikk** [comment]
@alexanderwallin Yes, I don't work for Trucknet anymore. And despite the fact that I wrote react-targem by myself, I was removed from the library's maintainers. 

I don't have a clear vision on how we can join the two libraries. Maybe you can clarify that?

**Comment by alexanderwallin** [comment]
Interesting 😬

Well the suite of tools I use is:

https://github.com/alexanderwallin/lioness
https://github.com/alexanderwallin/node-gettext
https://github.com/smhg/gettext-parser
https://github.com/laget-se/react-gettext-parser
https://github.com/laget-se/narp

And then there is

https://github.com/trucknet-io/react-targem
https://github.com/goooseman/gettext-utils

which has overlapping functionality as well as nice improvements and additions. It's a lot of tools! My (very fresh) idea is to collect and combine the best parts into something like

@lioness/gettext
@lioness/pot
@lioness/react
@lioness/extract
@lioness/sync

Well made I think it could be cohesive and useful. And easier to find!

**Comment by alexeychikk** [comment]
@alexanderwallin One of the main things `react-targem` is built around is the library's size. It has basically zero dependencies because I decided that the translation can be done without the need for the library to know all the possible plural forms of all the locales. Instead, I take the plural forms header from the `translations.json` and securely parse it into the function like this: https://github.com/trucknet-io/react-targem/blob/develop/src/localization/gettext.ts#L80 and memoize it.

This imposes additional responsibilities on the library user but dramatically reduces bundle size.

With this in mind, what exactly `@lioness/gettext` and `@lioness/react` will be responsible for? And could you please also add a few words on the rest of @lioness/... ?

**Comment by alexanderwallin** [comment]
@alexeychikk That makes perfect sense. 70k is unnecessary, and I've been wanting to modularise Lioness to support any gettext translation library, custom or existing, but haven't got there yet. Good move, and a clever solution!

----------

Okay, here are my initial thoughts:

#### @lioness/gettext

A gettext library. This would correspond to node-gettext or react-targem's gettext.ts.

#### @lioness/pot

A set of tools for dealing with POTs. Converting to and from JSON, merging, I saw something about optimizing for git. Those kinds of things. This would sort of act as a POT JSON standard spec, like gettext-parser.

#### @lioness/react

Set of components to localise React apps. This corresponds to the original Lioness lib or the React bits of react-targem.

#### @lioness/extract

Tool for extracting translatable content from JavaScript code. This is basically react-gettext-parser.

#### @lioness/sync

CLI utility for syncing translations to and from translation services. This is basically narp. narp has got a `push` and `pull` API that takes you from a change of a translatable string in your code base, to translating it online and having an up-to-date catalog in seconds, it's super handy. But very weirdly named...

---------

Almost all of these are usable independantly but fit into each other. Let me know what you think!

**Comment by alexeychikk** [comment]
Sounds neat.

I understand how we can extract what we already have into `@lioness/gettext` and `@lioness/react`.
But what about `@lioness/pot`, `@lioness/extract` and `@lioness/sync`? Do you basically want just to copy and rename `gettext-parser`,  `gettext-utils`,  and `narp` into `@lioness/...` just for the sake of namespace convenience/uniformity?

**Comment by alexanderwallin** [comment]
> Do you basically want just to copy and rename gettext-parser, gettext-utils, and narp into @lioness/... just for the sake of namespace convenience/uniformity?

Pretty much!

**Comment by alexeychikk** [comment]
@alexanderwallin What if `gettext-parser`, `react-gettext-parser`, `narp` or `gettext-utils` receives some critical update or just a good feature/improvement? We will have to track that manually and merge into the copied codebase. Or is there a better approach?

**Comment by alexeychikk** [comment]
@alexanderwallin May I ask why "lioness"? Does it mean something?

**Comment by alexanderwallin** [comment]
> @alexanderwallin What if gettext-parser, react-gettext-parser, narp or gettext-utils receives some critical update or just a good feature/improvement? We will have to track that manually and merge into the copied codebase. Or is there a better approach?

Could just have them as npm dependencies?

> @alexanderwallin May I ask why "lioness"? Does it mean something?

It comes from the _localization_ abbreviation _l10n_. "Lion" was already taken, so I went with "Lioness". :)
