### ISSUE TITLE
Set default locale and do not perform translation.

### ISSUE THREAD

**Issue by oolleegg55** [alexanderwallin/lioness#39]
Is it possible to set a current locale as default and do not perform translation if the original app language is the same as the current locale?

For example, all app strings are written in en_US and the current locale is en_US. Do I need to create a separate .po file for en_US locale and then transform messages.json and load into LionessProvider in this case?

**Comment by alexanderwallin** [comment]
You don't need translations for the default locale if you don't want to. `node-gettext` will always return the input string if it doesn't find a translation for it.

**Comment by oolleegg55** [comment]
But if there isn't a translation a warning is shown in case a debug mode is on.

**Comment by alexanderwallin** [comment]
Right, you want to keep debug mode on but not get warned about missing translations?

**Comment by oolleegg55** [comment]
Yes. I think if the debugger shows warnings it means that something is wrong.

**Comment by alexanderwallin** [comment]
`<LionessProvider>` now takes a [`gettextInstance` prop](https://github.com/alexanderwallin/lioness#lionessprovider-) where you can pass your own gettext instance. If you want to, you can create a [`node-gettext`](https://github.com/alexanderwallin/node-gettext) instance with debugging disabled, listen for errors via `yourInstance.on('error', handler)` and only log the error if the passed error message is not a missing translation message.

It's not the most beautiful thing, but it should do the job. Personally I always creating a translation for the default language as well, as that makes more sense to me technically.

Let me know if you have any more thoughts or questions!
