### ISSUE TITLE
automatic extration using component interpolation

### ISSUE THREAD

**Issue by marksteele** [alexanderwallin/lioness#40]
Not really an issue but more of a question on extracting things.

I've got the workflow of extracting strings working reasonably well except for when things are getting interpolated inside a translation.

```
{{ link:Link text here }}
```

I'm using the same configuration for react-gettext-parser:

```
funcArgumentsMap: {
    tc: ["msgid", null],
    tcn: ["msgid", "msgid_plural", null, null],
    tcp: ["msgctxt", "msgid", null],
    tcnp: ["msgctxt", "msgid", "msgid_plural", null, null],
    t: ["msgid"],
    tn: ["msgid", "msgid_plural", null],
    tp: ["msgctxt", "msgid"],
    tnp: ["msgctxt", "msgid", "msgid_plural", null]
  },
  componentPropsMap: {
    T: {
      message: "msgid",
      messagePlural: "msgid_plural",
      context: "msgctxt",
      comment: "comment"
    }
  }
```

Was just wondering if there's a magic sauce to extract those interpolated strings into the extraction process.

**Comment by alexanderwallin** [comment]
Hey Mark! Interpolations are supposed simply be part of the string that gets extracted and translated, and then interpolated at run-time. It's not meant to be interpolated before extraction.

Here's an example:

```js
// Here's the source languange in en_GB
<T
  message="I am walking on the {{ strong:pavement }}"
  strong={<strong />
}
```

You run the extractor and retrieve `"I am walking on the {{ strong:pavement }}"`. This is then translated to en_US as `"I am walking on the {{ strong:sidewalk }}"`. The `<T>` component will then interpolate this and put `sidewalk` inside a `<strong>` element.

Does that answer your question?
